global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # A ajouter plus tard : ton API FastAPI (ex: expose /metrics via prometheus-fastapi-instrumentator)
  # - job_name: "backend-api"
  #   static_configs:
  #     - targets: ["backend:8000"]